name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - SSP6904
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe
    attributes:
      label: Describe the issue
      description: Please give us more information our your issue.
  - type: checkboxes
    id: terms
    attributes:
      label: Terms of use
      description: By submitting this issue, you agree to follow our [Terms and conditions](https://ttnrtsite.me/terms/)
      options:
        - label: I agree to the Terms and conditions
          required: true